module: MaterialMotionCoreAnimation
module_version: 2.0.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionCoreAnimation.xcworkspace
  - -scheme
  - MaterialMotionCoreAnimation
github_url: https://github.com/material-motion/coreanimation-swift
github_file_prefix: https://github.com/material-motion/coreanimation-swift/tree/v2.0.0
