module: MaterialMotionCoreAnimationFamily
module_version: 1.1.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionCoreAnimationFamily.xcworkspace
  - -scheme
  - MaterialMotionCoreAnimationFamily
github_url: https://github.com/material-motion/material-motion-family-coreanimation-swift
github_file_prefix: https://github.com/material-motion/material-motion-family-coreanimation-swift/tree/v1.1.0
